include $(MOCADIR)/makefiles/StandardHeader.mk

OFILES=mxmllib.o \
       mxmlcommon.o \
       mxmljni.o 

EXTRACFLAGS=$(JCOPTIONS)

include $(MOCADIR)/makefiles/Library.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
