!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

LIBNAME=MOCAmxml

LIBPART=yes

OFILES=mxmllib.obj \
       mxmlcommon.obj \
       mxmljni.obj

!include $(MLIBDIR)\makefiles\Library.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
