include $(MLIBDIR)/makefiles/StandardHeader.mk

OFILES=mxmllib.o \
       mxmlcommon.o \
       mxmljni.o 

EXTRACFLAGS=$(JCOPTIONS)

include $(MLIBDIR)/makefiles/Library.mk
include $(MLIBDIR)/makefiles/StandardFooter.mk
