static char RCS_Id[] = "$Id$";
/*#START***********************************************************************
 *
 *  $URL$
 *  $Revision$
 *  $Author$
 *
 *  Description: Launcher for servicemgr.
 *
 *  $Copyright-Start$
 *
 *  Copyright (c) 2011
 *  Sam Corporation
 *  All Rights Reserved
 *
 *  This software is furnished under a corporate license for use on a
 *  single computer system and can be copied (with inclusion of the
 *  above copyright) only for use on such a system.
 *
 *  The information in this document is subject to change without notice
 *  and should not be construed as a commitment by Sam Corporation.
 *
 *  Sam Corporation assumes no responsibility for the use of the
 *  software described in this document on equipment which has not been
 *  supplied or approved by Sam Corporation.
 *
 *  $Copyright-End$
 *
 *#END*************************************************************************/

#include <moca.h>

#include <stdio.h>
#include <stdlib.h>

#include <mocagendef.h>
#include <mislib.h>
#include <oslib.h>

#include "servicemgr.h"

long DumpEnvironment(char *envname)
{

    long status;
    char *name,
         *value;
    void *ctx;
    FILE *outfile;

    /*
     * Determine the registry file we'll be using and set the
     * MOCA_ENVNAME and MOCA_REGISTRY environment variables.
     */
    status = SetupRegistryFile(envname);
    if (status != 0)
    {
        printf("Could not successfully create env.bat file\n");
        return 1;
    }

    /* Open the env.bat file. */
    outfile = fopen("env.bat", "w");
    if (!outfile)
    {
        printf("Could not open env.bat file for writing\n");
        return 1;
    }

    printf("Creating env.bat file for environment...\n\n");

    /*
     * Write a nice header with a date/time stamp to the env.bat file.
     */
    fprintf(outfile, "REM\n");
    fprintf(outfile, "REM Generated by servicmgr on %s at %s.\n",
            misFormatDate("mm/dd/yyyy"),
            misFormatTime("hh:mm:ss"));
    fprintf(outfile, "REM\n\n");

    /*
     * Write the MOCA_ENVNAME and MOCA_REGISTRY values to the env.bat
     * file. We have to do these manually because they won't exist within
     * the registry file.
     */
    fprintf(outfile, "set %s=%s\n", ENV_ENVNAME,  envname);
    fprintf(outfile, "set %s=%s\n", ENV_REGISTRY, getenv(ENV_REGISTRY));

    /*
     * Write each environment variable from the registry to the env.bat file.
     */
    ctx = NULL;
    while ((osEnumerateRegistry(REGSEC_ENVIRONMENT, &ctx, &name, &value)))
    {
        fprintf(outfile, "set %s=%s\n", name, value);
    }

    fclose(outfile);

    printf("    Environment: %s\n", envname);
    printf("       Registry: %s\n\n", getenv(ENV_REGISTRY));

    printf("Done\n");

    return 0;
}
