!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

APPNAME=msql

OFILES=commands.obj \
       connection.obj \
       edit.obj \
       history.obj \
       msql.obj \
       print.obj \
       process.obj \
       read.obj \
       script.obj \
       spool.obj 

EXTRALINKFLAGS=/stack:20000000

!include $(MLIBDIR)\makefiles\Application.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
