include $(MLIBDIR)/makefiles/StandardHeader.mk

APPNAME=msql

OFILES=commands.o \
       connection.o \
       edit.o \
       history.o \
       msql.o \
       print.o \
       process.o \
       read.o \
       script.o \
       spool.o 

include $(MLIBDIR)/makefiles/Application.mk
include $(MLIBDIR)/makefiles/StandardFooter.mk
