include $(MLIBDIR)/makefiles/StandardHeader.mk

APPNAME=socksrvprc

OFILES=execute.o \
       signal.o \
       socksrvprc.o

include $(MLIBDIR)/makefiles/Application.mk
include $(MLIBDIR)/makefiles/StandardFooter.mk
