include $(MOCADIR)/makefiles/StandardHeader.mk

APPNAME=socksrvmgr

OFILES=cons_Echo.o \
       cons_KillAllServers.o \
       cons_KillConn.o \
       cons_KillServer.o \
       cons_List.o \
       cons_Password.o \
       cons_Quit.o \
       cons_SetMinServers.o \
       cons_SetMaxCommands.o \
       cons_SetMaxServers.o \
       cons_SetTraceLevel.o \
       cons_ShowOptions.o \
       cons_Shutdown.o \
       cons_command.o \
       console.o \
       environment.o \
       init.o \
       list.o \
       server.o \
       signal.o \
       socksrvmgr.o 

include $(MOCADIR)/makefiles/Application.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
