include $(MLIBDIR)/makefiles/StandardDirHeader.mk

SUBDIR=dblib \
       evtlib \
       jnilib \
       madlib \
       mcclib \
       mislib \
       mxmllib \
       oslib \
       sqllib \
       srvlib \
       mocalib \
       mocabase \
       mocaxml 

include $(MLIBDIR)/makefiles/StandardDirFooter.mk
