!include $(MOCADIR)\makefiles\StandardHeader.mk.win32

LIBNAME=MOCAdb

LIBPART=yes

OFILES=dblib.obj

!include $(MOCADIR)\makefiles\Library.mk.win32
!include $(MOCADIR)\makefiles\StandardFooter.mk.win32
