include $(MLIBDIR)/makefiles/StandardDirHeader.mk

SUBDIR=createctl \
       dbupgrade \
       installsql \
       mbuild \
       mgendoc \
       mbxadmin \
       mbxrcvprc \
       mload \
       mloadall \
       mocaserver \
       mpasswd \
       msql \
       socksrvmgr \
       socksrvprc \
       runtask \
       wsdeploy

include $(MLIBDIR)/makefiles/StandardDirFooter.mk
