!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

LIBNAME=MOCAdb

LIBPART=yes

OFILES=dblib.obj

!include $(MLIBDIR)\makefiles\Library.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
