include $(MOCADIR)/makefiles/StandardHeader.mk

OFILES=mccClose.o \
       mccDisableAutoCommit.o \
       mccEnableAutoCommit.o \
       mccError.o \
       mccExecStr.o \
       mccInit.o \
       mccLogin.o \
       mccLogout.o \
       mccSetApplicationID.o \
       mccSetupEnvironment.o 

include $(MOCADIR)/makefiles/Library.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
