!include $(MOCADIR)\makefiles\StandardHeader.mk.win32

APPNAME=socksrvprc

OFILES=execute.obj \
       signal.obj \
       socksrvprc.obj

!include $(MOCADIR)\makefiles\Application.mk.win32
!include $(MOCADIR)\makefiles\StandardFooter.mk.win32
