include $(MOCADIR)/makefiles/StandardHeader.mk

APPNAME=socksrvprc

OFILES=execute.o \
       signal.o \
       socksrvprc.o

include $(MOCADIR)/makefiles/Application.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
