include $(MOCADIR)/makefiles/StandardHeader.mk

LIBNAME=MADtest

OFILES=MOCAlicense.o \
       MOCAversion.o \
       testMad.o \
       testMadTaskId.o \
       testMadCrash.o \
       testPerformance.o 

EXTRALIBS=-lm

include $(MOCADIR)/makefiles/Component.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
