include $(MLIBDIR)/makefiles/StandardHeader.mk

LIBNAME=MADtest

OFILES=MOCAlicense.o \
       MOCAversion.o \
       testMad.o \
       testMadTaskId.o \
       testMadCrash.o \
       testPerformance.o 

EXTRALIBS=-lm

include $(MLIBDIR)/makefiles/Component.mk
include $(MLIBDIR)/makefiles/StandardFooter.mk
