!include $(MOCADIR)\makefiles\StandardHeader.mk.win32

APPNAME=installsql

OFILES=installsql.obj

!include $(MOCADIR)\makefiles\Application.mk.win32
!include $(MOCADIR)\makefiles\StandardFooter.mk.win32

