//
// This file is automatically generated do not edit
// InstallShield Include file
//

#define PRODUCT_VERSION    "2013.2.2.15"
#define SERVER_DISK_USAGE  "@SERVER_DISK_USAGE@"
#define CLIENT_DISK_USAGE  "@CLIENT_DISK_USAGE@"
