!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

APPNAME=createctl

OFILES=createctl.obj

!include $(MLIBDIR)\makefiles\Application.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32

