include $(MOCADIR)/makefiles/StandardHeader.mk

IFILES=cmdlib.h \
       common.h \
       copyright.h \
       dblib.h \
       evtlib.h \
       jnilib.h \
       madlib.h \
       mcclib.h \
       mislib.h \
       moca.h \
       mocacolwid.h \
       mocaconfig.h \
       mocaddl.h \
       mocaerr.h \
       mocagendef.h \
       mocasymbols.h \
       mocatbldef.h \
       mocaversion.h \
       mxmllib.h \
       oslib.h \
       sqlDataTypes.h \
       sqlDataTypesH2.h \
       sqlDataTypesObsolete.h \
       sqlDataTypesOracle.h \
       sqlDataTypesSQLServer.h \
       sqllib.h \
       srvlib.h \
       usrtbldef.h \
       vartbldef.h

TARGETS=$(INCDIR)/cmdlib.h \
	$(INCDIR)/common.h \
	$(INCDIR)/copyright.h \
	$(INCDIR)/dblib.h \
	$(INCDIR)/evtlib.h \
	$(INCDIR)/jnilib.h \
	$(INCDIR)/madlib.h \
	$(INCDIR)/mcclib.h \
	$(INCDIR)/mislib.h \
	$(INCDIR)/moca.h \
	$(INCDIR)/mocacolwid.h \
	$(INCDIR)/mocaconfig.h \
	$(INCDIR)/mocaddl.h \
	$(INCDIR)/mocaerr.h \
	$(INCDIR)/mocagendef.h \
	$(INCDIR)/mocasymbols.h \
	$(INCDIR)/mocatbldef.h \
	$(INCDIR)/mocaversion.h \
	$(INCDIR)/mxmllib.h \
	$(INCDIR)/oslib.h \
	$(INCDIR)/sqlDataTypes.h \
	$(INCDIR)/sqlDataTypesH2.h \
	$(INCDIR)/sqlDataTypesObsolete.h \
	$(INCDIR)/sqlDataTypesOracle.h \
	$(INCDIR)/sqlDataTypesSQLServer.h \
	$(INCDIR)/sqllib.h \
	$(INCDIR)/srvlib.h \
	$(INCDIR)/usrtbldef.h \
	$(INCDIR)/vartbldef.h 

default:
	@echo "Your options are:  "
	@echo "    make install:    copy all files to include directory"
	@echo "    make clean:      clean directory of unchanged files"

dinstall: $(TARGETS)

debug: $(TARGETS)

install: $(TARGETS)

clean:

all:

$(INCDIR)/cmdlib.h: cmdlib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) cmdlib.h

$(INCDIR)/common.h: common.h
	@$(INSTALL) $(INCMODE) $(INCDIR) common.h

$(INCDIR)/copyright.h: copyright.h
	@$(INSTALL) $(INCMODE) $(INCDIR) copyright.h

$(INCDIR)/dblib.h: dblib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) dblib.h

$(INCDIR)/evtlib.h: evtlib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) evtlib.h

$(INCDIR)/jnilib.h: jnilib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) jnilib.h

$(INCDIR)/madlib.h: madlib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) madlib.h

$(INCDIR)/mcclib.h: mcclib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mcclib.h

$(INCDIR)/mislib.h: mislib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mislib.h

$(INCDIR)/moca.h: moca.h
	@$(INSTALL) $(INCMODE) $(INCDIR) moca.h

$(INCDIR)/mocacolwid.h: mocacolwid.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocacolwid.h

$(INCDIR)/mocaconfig.h: mocaconfig.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocaconfig.h

$(INCDIR)/mocaddl.h: mocaddl.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocaddl.h

$(INCDIR)/mocaerr.h: mocaerr.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocaerr.h

$(INCDIR)/mocagendef.h: mocagendef.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocagendef.h

$(INCDIR)/mocasymbols.h: mocasymbols.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocasymbols.h

$(INCDIR)/mocatbldef.h: mocatbldef.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocatbldef.h

$(INCDIR)/mocaversion.h: mocaversion.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mocaversion.h

$(INCDIR)/mxmllib.h: mxmllib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) mxmllib.h

$(INCDIR)/oslib.h: oslib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) oslib.h

$(INCDIR)/sqlDataTypes.h: sqlDataTypes.h
	@$(INSTALL) $(INCMODE) $(INCDIR) sqlDataTypes.h

$(INCDIR)/sqlDataTypesH2.h: sqlDataTypesH2.h
	@$(INSTALL) $(INCMODE) $(INCDIR) sqlDataTypesH2.h

$(INCDIR)/sqlDataTypesObsolete.h: sqlDataTypesObsolete.h
	@$(INSTALL) $(INCMODE) $(INCDIR) sqlDataTypesObsolete.h

$(INCDIR)/sqlDataTypesOracle.h: sqlDataTypesOracle.h
	@$(INSTALL) $(INCMODE) $(INCDIR) sqlDataTypesOracle.h

$(INCDIR)/sqlDataTypesSQLServer.h: sqlDataTypesSQLServer.h
	@$(INSTALL) $(INCMODE) $(INCDIR) sqlDataTypesSQLServer.h

$(INCDIR)/sqllib.h: sqllib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) sqllib.h

$(INCDIR)/srvlib.h: srvlib.h
	@$(INSTALL) $(INCMODE) $(INCDIR) srvlib.h

$(INCDIR)/usrtbldef.h: usrtbldef.h
	@$(INSTALL) $(INCMODE) $(INCDIR) usrtbldef.h

$(INCDIR)/vartbldef.h: vartbldef.h
	@$(INSTALL) $(INCMODE) $(INCDIR) vartbldef.h

hinstall: install
