!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

APPNAME=installsql

OFILES=installsql.obj

!include $(MLIBDIR)\makefiles\Application.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32

