!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

APPNAME=mocaserver

OFILES=mocaserver.obj

!include $(MLIBDIR)\makefiles\Application.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32

