!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

APPNAME=dbupgrade

OFILES=dbupgrade.obj

!include $(MLIBDIR)\makefiles\Application.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32

