!include $(MOCADIR)\makefiles\StandardHeader.mk.win32

APPNAME=servicemgr

OFILES=dump.obj \
       environment.obj \
       registry.obj \
       servicemgr.obj

!include $(MOCADIR)\makefiles\Application.mk.win32
!include $(MOCADIR)\makefiles\StandardFooter.mk.win32

