include $(MOCADIR)/makefiles/StandardHeader.mk

LIBNAME=MOCAxml

OFILES=MOCAlicense.o \
       MOCAversion.o \
       mocaAddXMLAttribute.o \
       mocaAddXMLElement.o \
       mocaAddXMLTextNode.o \
       mocaApplyStylesheet.o \
       mocaConvertResultSetToXML.o \
       mocaConvertXMLToResultSet.o \
       mocaCreateXMLDocument.o \
       mocaGetXML.o \
       mocaGetXMLChildNodes.o \
       mocaGetXMLElementsByTagName.o \
       mocaGetXMLNodeValues.o \
       mocaNormalizeXML.o \
       mocaParseXML.o \
       mocaRemoveXMLChild.o \
       mocaStartXMLParser.o \
       mocaStopXMLParser.o \
       mocaWriteXMLFile.o 

include $(MOCADIR)/makefiles/Component.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
