!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

LIBNAME=MOCAxml

OFILES=MOCAlicense.obj \
       MOCAversion.obj \
       mocaAddXMLAttribute.obj \
       mocaAddXMLElement.obj \
       mocaAddXMLTextNode.obj \
       mocaApplyStylesheet.obj \
       mocaConvertResultSetToXML.obj \
       mocaConvertXMLToResultSet.obj \
       mocaCreateXMLDocument.obj \
       mocaGetXML.obj \
       mocaGetXMLChildNodes.obj \
       mocaGetXMLElementsByTagName.obj \
       mocaGetXMLNodeValues.obj \
       mocaNormalizeXML.obj \
       mocaParseXML.obj \
       mocaRemoveXMLChild.obj \
       mocaStartXMLParser.obj \
       mocaStopXMLParser.obj \
       mocaWriteXMLFile.obj 

!include $(MLIBDIR)\makefiles\Component.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
