!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

LIBNAME=MOCAjni

LIBPART=yes

OFILES=argmap.obj \
       dbcalls.obj \
       executeCOM.obj \
       extract.obj \
       initialize.obj \
       jnilib.obj \
       mcccalls.obj \
       miscalls.obj \
       native.obj \
       oscalls.obj \
       results.obj \
       server.obj \
       srvcalls.obj

results.obj: results.c results.h
	$(CC) $(CFLAGS) -c results.c -Fo$@

native.obj: native.c native.h
	$(CC) $(CFLAGS) -c native.c -Fo$@

javalib.obj: javalib.c
	$(CC) $(CFLAGS) -c javalib.c -Fo$@

#results.h: $(MLIBDIR)\lib\moca-server.jar
#	"$(JAVA_HOME)\bin\javah" -classpath "$(MLIBDIR)\build\core\classes;$(MLIBDIR)\build\server\classes;$(MLIBDIR)\build\native\classes;$(MLIBDIR)\lib\moca-core.jar;$(MLIBDIR)\lib\moca-native.jar;$(MLIBDIR)\lib\moca-server.jar" -jni -o results.h com.redprairie.moca.server.legacy.WrappedResults
#
#native.h: $(MLIBDIR)\lib\moca-server.jar
#	"$(JAVA_HOME)\bin\javah" -classpath "$(MLIBDIR)\build\core\classes;$(MLIBDIR)\build\native\classes;$(MLIBDIR)\build\server\classes;$(MLIBDIR)\lib\moca-core.jar;$(MLIBDIR)\lib\moca-native.jar;$(MLIBDIR)\lib\moca-server.jar" -jni -o native.h com.redprairie.moca.server.legacy.InternalNativeProcess

!include $(MLIBDIR)\makefiles\Library.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
