include $(MLIBDIR)/makefiles/StandardHeader.mk

OFILES=mad.o \
       mad_msg.o \
       mad_queue.o \
       mad_async_queue.o \
       mad_thread_pool.o \
       mad_async_send.o \
       mad_send.o \
       mad_buffered_writer.o \
       mad_byte_buffer.o \
       mad_mutex.o \
       mad_time.o \
       mad_interval.o 

include $(MLIBDIR)/makefiles/Library.mk
include $(MLIBDIR)/makefiles/StandardFooter.mk
