include $(MOCADIR)/makefiles/StandardHeader.mk

LIBNAME=MOCAtest

OFILES=MOCAlicense.o \
       MOCAversion.o \
       testBigData.o \
       testBlowfish.o \
       testCache.o \
       testCompiledCommand.o \
       testConvertToBinaryPointer.o \
       testExecute.o \
       testGenericPointer.o \
       testGetNeededElementPointer.o \
       testGetNeededElementResult.o \
       testIndirectCrash.o \
       testKeepalive.o \
       testNativeOutput.o \
       testNullReturn.o \
       testResolvedError.o \
       testRetrieveResults.o \
       testSavepoint.o \
       testSimpleComponent.o \
       testSimpleSQL.o \
       testSrvExecuteAfterRollback.o \
       testSleep.o \
       testSQLBind.o \
       testSQLError.o \
       testUntilZero.o \
       testVar.o

EXTRALIBS=-lm

include $(MOCADIR)/makefiles/Component.mk
include $(MOCADIR)/makefiles/StandardFooter.mk
