include $(MLIBDIR)/makefiles/StandardHeader.mk

LIBNAME=MOCAbase

OFILES=mocaDumpCore.o \
       mocaEncryptRPBF.o \
       mocaExecuteOsCommand.o \
       mocaGetFileInfo.o \
       mocaGetTraceLevels.o \
       mocaListDiskDrives.o \
       mocaPrintFile.o \
       mocaSetProcessPriority.o \
       mocaSprintfData.o

EXTRALIBS=-lm

include $(MLIBDIR)/makefiles/Component.mk
include $(MLIBDIR)/makefiles/StandardFooter.mk
