!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

LIBNAME=MOCAbase

OFILES=mocaDumpCore.obj \
       mocaEncryptRPBF.obj \
       mocaExecuteOsCommand.obj \
       mocaGetFileInfo.obj \
       mocaGetTraceLevels.obj \
       mocaListDiskDrives.obj \
       mocaPrintFile.obj \
       mocaSetProcessPriority.obj \
       mocaSprintfData.obj

!include $(MLIBDIR)\makefiles\Component.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
