!include $(MLIBDIR)\makefiles\StandardHeader.mk.win32

APPNAME=mload_all

OFILES=mload_all.obj

!include $(MLIBDIR)\makefiles\Application.mk.win32
!include $(MLIBDIR)\makefiles\StandardFooter.mk.win32
